function  [Pss_on, Bss_on, stable_state]=StableFocalPoints_on(P_env, gamma_B, kappa_P, delta_P, kappa_B,alpha_I, gamma_R,delta_B, R_on, m_on, beta_on)


Pss_on_1=(beta_on*delta_B*delta_P - (P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - R_on*alpha_I*kappa_B - delta_P*kappa_B + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*(delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I)) - (delta_P*gamma_B*kappa_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/((delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I));
Bss_on_1=-(beta_on*delta_B*delta_P - (P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - R_on*alpha_I*kappa_B - delta_P*kappa_B + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*gamma_B*(delta_P + R_on*alpha_I)*(beta_on*delta_B - kappa_B + R_on*beta_on*delta_B*gamma_R));
  
%%
Pss_on_2=((P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - delta_P*kappa_B - R_on*alpha_I*kappa_B + beta_on*delta_B*delta_P + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*(delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I)) - (delta_P*gamma_B*kappa_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/((delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I));
Bss_on_2=-((P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - delta_P*kappa_B - R_on*alpha_I*kappa_B + beta_on*delta_B*delta_P + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*gamma_B*(delta_P + R_on*alpha_I)*(beta_on*delta_B - kappa_B + R_on*beta_on*delta_B*gamma_R));

%%
Jac1=[[ - delta_P - R_on*alpha_I,              -(P_env*gamma_B*kappa_P)/(Bss_on_1*gamma_B + 1)^2]
[          -Bss_on_1*delta_B*m_on, delta_B*(beta_on - Pss_on_1*m_on) - kappa_B/(R_on*gamma_R + 1)]];
%%

Jac2=[[ - delta_P - R_on*alpha_I,              -(P_env*gamma_B*kappa_P)/(Bss_on_2*gamma_B + 1)^2]
[          -Bss_on_2*delta_B*m_on, delta_B*(beta_on - Pss_on_2*m_on) - kappa_B/(R_on*gamma_R + 1)]];
%%

%%
eig1=double(eig((Jac1)))

eig2=double(eig((Jac2)))

%% check stability
if sum(real(eig1)<0)==2 && sum(real(eig2)<0)~=2 % the real parts of the two eigenvalues are negative
    Pss_on=Pss_on_1;
    Bss_on=Bss_on_1;
    
    stable_state=1; % only the first one is stable
    
elseif sum(real(eig1)<0)~=2 && sum(real(eig2)<0)==2 % the real parts of all eigenvalues are negative
    Pss_on=Pss_on_2;
    Bss_on=Bss_on_2;
    
    stable_state=2; % only the first one is stable
    
elseif   sum(real(eig1)<0)~=2 && sum(real(eig2)<0)~=2 % the real parts of all eigenvalues are negative
    Pss_on=real(Pss_on_1);
    Bss_on=real(Pss_on_2);
    
    stable_state=4; % both are stable
    disp('Warning: none is stable')
    
elseif   sum(real(eig1)<0)==2 && sum(real(eig2)<0)==2 % the real parts of all eigenvalues are negative
    Pss_on=Pss_on_1;
    Bss_on=Bss_on_1;
    
    stable_state=3; % both are stable
    disp('Warning: both focal points are stable')
    
end


end

