close all
clear all
clc


syms P_env gamma_B kappa_P delta_P kappa_B alpha_I  gamma_R delta_B P_minus P_plus R_off R_on K_off m_on beta_on



assume(P_env, 'positive');
assume(gamma_B , 'positive');
assume( kappa_P, 'positive');
assume(delta_P, 'positive');
assume(kappa_B, 'positive');
assume(alpha_I, 'positive');
assume(gamma_R, 'positive');
assume(delta_B, 'positive');
assume(P_minus, 'positive');
assume(P_plus, 'positive');
assume(R_on, 'positive');
assume(m_on, 'positive');
assume(beta_on, 'positive');
%%
%%
syms P B
%%

dPdt_on=  (P_env*kappa_P/(1+gamma_B*B))-P*(alpha_I*R_on+delta_P); % Pathogen load ODE
dBdt_on=  (kappa_B/((1+gamma_R*R_on)))*(1-B)-delta_B*(m_on*P-beta_on)*B;
%%
system_on=[dPdt_on dBdt_on];
sol=solve(system_on, [P B]);

%%
Pss_on_1=(beta_on*delta_B*delta_P - (P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - R_on*alpha_I*kappa_B - delta_P*kappa_B + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*(delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I)) - (delta_P*gamma_B*kappa_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/((delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I));
Bss_on_1=-(beta_on*delta_B*delta_P - (P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - R_on*alpha_I*kappa_B - delta_P*kappa_B + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*gamma_B*(delta_P + R_on*alpha_I)*(beta_on*delta_B - kappa_B + R_on*beta_on*delta_B*gamma_R))
  
%%
Pss_on_2=((P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - delta_P*kappa_B - R_on*alpha_I*kappa_B + beta_on*delta_B*delta_P + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*(delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I)) - (delta_P*gamma_B*kappa_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/((delta_B*m_on + R_on*delta_B*gamma_R*m_on)*(delta_P + R_on*alpha_I))
Bss_on_2=-((P_env^2*R_on^2*delta_B^2*gamma_R^2*kappa_P^2*m_on^2 + 2*P_env^2*R_on*delta_B^2*gamma_R*kappa_P^2*m_on^2 + P_env^2*delta_B^2*kappa_P^2*m_on^2 - 2*P_env*R_on^3*alpha_I*beta_on*delta_B^2*gamma_R^2*kappa_P*m_on - 4*P_env*R_on^2*alpha_I*beta_on*delta_B^2*gamma_R*kappa_P*m_on - 2*P_env*R_on^2*alpha_I*delta_B*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on^2*alpha_I*delta_B*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*R_on^2*beta_on*delta_B^2*delta_P*gamma_R^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*beta_on*delta_B^2*kappa_P*m_on - 2*P_env*R_on*alpha_I*delta_B*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*R_on*alpha_I*delta_B*kappa_B*kappa_P*m_on - 4*P_env*R_on*beta_on*delta_B^2*delta_P*gamma_R*kappa_P*m_on - 2*P_env*R_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B*kappa_P*m_on + 2*P_env*R_on*delta_B*delta_P*gamma_R*kappa_B*kappa_P*m_on - 2*P_env*beta_on*delta_B^2*delta_P*kappa_P*m_on - 2*P_env*delta_B*delta_P*gamma_B*kappa_B*kappa_P*m_on + 2*P_env*delta_B*delta_P*kappa_B*kappa_P*m_on + R_on^4*alpha_I^2*beta_on^2*delta_B^2*gamma_R^2 + 2*R_on^3*alpha_I^2*beta_on^2*delta_B^2*gamma_R - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_B*gamma_R*kappa_B - 2*R_on^3*alpha_I^2*beta_on*delta_B*gamma_R*kappa_B + 2*R_on^3*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R^2 + R_on^2*alpha_I^2*beta_on^2*delta_B^2 - 2*R_on^2*alpha_I^2*beta_on*delta_B*gamma_B*kappa_B - 2*R_on^2*alpha_I^2*beta_on*delta_B*kappa_B + R_on^2*alpha_I^2*gamma_B^2*kappa_B^2 + 2*R_on^2*alpha_I^2*gamma_B*kappa_B^2 + R_on^2*alpha_I^2*kappa_B^2 + 4*R_on^2*alpha_I*beta_on^2*delta_B^2*delta_P*gamma_R - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_B*gamma_R*kappa_B - 4*R_on^2*alpha_I*beta_on*delta_B*delta_P*gamma_R*kappa_B + R_on^2*beta_on^2*delta_B^2*delta_P^2*gamma_R^2 + 2*R_on*alpha_I*beta_on^2*delta_B^2*delta_P - 4*R_on*alpha_I*beta_on*delta_B*delta_P*gamma_B*kappa_B - 4*R_on*alpha_I*beta_on*delta_B*delta_P*kappa_B + 2*R_on*alpha_I*delta_P*gamma_B^2*kappa_B^2 + 4*R_on*alpha_I*delta_P*gamma_B*kappa_B^2 + 2*R_on*alpha_I*delta_P*kappa_B^2 + 2*R_on*beta_on^2*delta_B^2*delta_P^2*gamma_R - 2*R_on*beta_on*delta_B*delta_P^2*gamma_B*gamma_R*kappa_B - 2*R_on*beta_on*delta_B*delta_P^2*gamma_R*kappa_B + beta_on^2*delta_B^2*delta_P^2 - 2*beta_on*delta_B*delta_P^2*gamma_B*kappa_B - 2*beta_on*delta_B*delta_P^2*kappa_B + delta_P^2*gamma_B^2*kappa_B^2 + 2*delta_P^2*gamma_B*kappa_B^2 + delta_P^2*kappa_B^2)^(1/2) - delta_P*kappa_B - R_on*alpha_I*kappa_B + beta_on*delta_B*delta_P + delta_P*gamma_B*kappa_B + R_on*alpha_I*beta_on*delta_B + R_on*alpha_I*gamma_B*kappa_B - P_env*delta_B*kappa_P*m_on + R_on*beta_on*delta_B*delta_P*gamma_R + R_on^2*alpha_I*beta_on*delta_B*gamma_R - P_env*R_on*delta_B*gamma_R*kappa_P*m_on)/(2*gamma_B*(delta_P + R_on*alpha_I)*(beta_on*delta_B - kappa_B + R_on*beta_on*delta_B*gamma_R))
 

%%
%jacobian(system_on, [P B])

%%
Jac=[[ - delta_P - R_on*alpha_I,              -(P_env*gamma_B*kappa_P)/(B*gamma_B + 1)^2]
[          -B*delta_B*m_on, delta_B*(beta_on - P*m_on) - kappa_B/(R_on*gamma_R + 1)]];

%%
eig1=(eig(((subs(subs(Jac, B, Bss_on_1), P, Pss_on_1)))))

%%

eig2=(eig(((subs(subs(Jac, B, Bss_on_2), P, Pss_on_2)))))

%%
